updates

diff --git a/scripts/checktls b/scripts/checktls
--- a/scripts/checktls
+++ b/scripts/checktls
@@ -9,7 +9,7 @@ if [[ -z "$1" ]]; then
     host="$(hostname)"
     readarray -t ports < <(postfix_smtp_ports)
     if [[ "${#ports[@]}" = 0 ]]; then
-        echo -e "${cRed}ERROR${cReset} No SMTP ports found" >&2
+        echo "${cRed}ERROR${cReset} No SMTP ports found" >&2
         exit 1
     fi
     for port in "${ports[@]}"; do
@@ -22,7 +22,7 @@ fi
 exitcode=0
 
 for server in "${servers[@]}"; do
-    echo -e "${cWhiteBright}Checking TLS on${cReset} ${cCyan}${server}${cReset}"
+    echo "${cWhiteLight}Checking TLS on${cReset} ${cCyan}${server}${cReset}"
     set +e
     openssl s_client -connect "$server" \
         -verify_return_error \
@@ -30,16 +30,16 @@ for server in "${servers[@]}"; do
     code="$?"
     set -e
     if [[ "$code" = 0 ]]; then
-        echo -e "${cGreen}PASS${cReset} TLS passed for" \
+        echo "${cGreen}PASS${cReset} TLS passed for" \
             "${cCyan}${server}${cReset}"
     else
         exitcode="$code"
-        echo -e "${cRed}ERROR${cReset} TLS failed for" \
+        echo "${cRed}ERROR${cReset} TLS failed for" \
             "${cYellow}${server}${cReset} with exit code ${code}"
     fi
 done
 
 if [[ "$exitcode" != 0 ]]; then
-    echo -e "${cRed}TLS check failed!${cReset}"
+    echo "${cRed}TLS check failed!${cReset}"
 fi
 exit "$exitcode"
